### ISSUE TITLE
How to change the language of columns?

### ISSUE THREAD

**Issue by slamonega** [HandsOnDataViz/leaflet-maps-with-google-sheets#129]
I need to change Name and Description to Spanish (Nombre, Descripcion), How can I do that? I try to figure out from maps.js but I couldnt.

Thanks, and regards from Argentina.

Sebas

**Comment by JackDougherty** [comment]
The simplest solution is to not change the Google Sheet column names, since those are not visible in the public map.

But If you wish to change column names in the Google Sheet, such as 'Name' to 'Nombre' 
then you need to do a search to find 'name' (with single-quote marks) and change to 'nombre' in this section of the scripts/map.js code:

https://github.com/HandsOnDataViz/leaflet-maps-with-google-sheets/blob/bf5e117ca3a5639fd58e02c5cf48ce13a0a52f01/scripts/map.js#L130

Repeat to change 'description' to 'descripcion' but note that it appears 4 times in the scripts/map.js code.

If you wish to change other labels in the Google Sheet, some appear in scripts/constants.js

buena suerte

**Comment by slamonega** [comment]
Thanks Jack!

**Comment by slamonega** [comment]
Jack, what's about 'Group', I need to change to 'Categorías', I tried but I
couldnt. Names and Descriptions works fine with the changes.
Sebas

**Comment by JackDougherty** [comment]
Your question has grown larger than what you originally asked.

The relevant section about the 'Group' code is here::
https://github.com/HandsOnDataViz/leaflet-maps-with-google-sheets/blob/bf5e117ca3a5639fd58e02c5cf48ce13a0a52f01/scripts/map.js#L65

But you need JavaScript coding skills to make accurate edits. I cannot provide additional help with your revisions.

**Comment by slamonega** [comment]
Thanks Jack, I resolved it with the line 73   var group = points[i].Categoría; and others .Groups references.
