### ISSUE TITLE
Point Search

### ISSUE THREAD

**Issue by adeafblindman** [HandsOnDataViz/leaflet-maps-with-google-sheets#134]
Is it possible to have the search bar search point names?

**Comment by JackDougherty** [comment]
The Leaflet map search tool (magnifying glass icon) is pre-designed to search place names on the underlying base map, so there is no easy way to modify it to search point names in the Google Sheet data.

Two options come to mind:
1.  Since the Google Sheet data with point names is publicly, you could create a link for users to go to that page and search
2. See also the Leaflet Searchable Point Map tutorial and template by Derek Eder in our book (https://handsondataviz.org/leaflet-searchable-map.html), which is designed to help users search and filter numerous points on the map, such as locations for flu shots. See demo (https://searchable-map-template-csv.netlify.app)

**Comment by adeafblindman** [comment]
Thanks, using the template for a custom game with over 100 players, having players search for their unit would be nice. https://adeafblindman.github.io/MetaCampaignMap/

I'll look into the Leaflet Searchable Point Map tutorial to see if that works for this case.
